wait on axis commands
AllenNeuralDynamics/TigerASI pull request #56
Opened 2023-10-18 20:35 UTC by adamkglaser

adding commands to wait on single axis.

2023-11-14 19:52 UTC, adamkglaser commented
Successfully tested this with hardware. @Poofjunior when you have a chance to look at this small addition that would be great. Hopefully a simple merge.

2023-11-28 00:42 UTC, Poofjunior requested changes
Ok, have a look at the dev/wait_on_axis_remix branch. If that looks good, let's merge that branch into this one and then merge this one into main.

2023-11-28 04:20 UTC, adamkglaser reviewed
Looks good to me

2023-11-28 04:30 UTC, Poofjunior approved these changes

2023-11-28 04:30 UTC, merged